name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        oc:
          - "4.12"
          - "4.13"
          - "4.14"
          - "4.15"
          - "4.16"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: "v${{ matrix.oc }}"
          file: "v${{ matrix.oc }}/Dockerfile"
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: linux/amd64,linux/arm64
          tags: |
            docker.io/adamab/oc:v${{ matrix.oc }}
